version: '3'
services:
  muscle_segmentation_jip:
    build: ./
    shm_size: '2gb'
    container_name: ct_muscle_seg_jip
    hostname: ct_muscle_seg_jip
    environment:
      - WORKFLOW_DIR=/app/workflow
      - BATCH_NAME=batch1
      - OPERATOR_IN_DIR=input
      - OPERATOR_OUT_DIR=output
      - PYTHONBUFFERED=1
    command: python3 -u /app/run_container_jip.py
    volumes:
    - ./workflow:/app/workflow
